# Generated by Django 2.1.5 on 2019-02-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='creater',
            field=models.CharField(default='admin', max_length=10),
            preserve_default=False,
        ),
    ]
