# Generated by Django 2.1.5 on 2019-02-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_creater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='creater',
            new_name='writer',
        ),
    ]
